In [79]:
## Imports
import numpy as np

### Question - 4

In [ ]:
#  a)  A 1-D array called zeros having 10 elements and all the elements are set to zero.
npZeros = np.zeros(10)
print(f"A) 1-D array called zeros having 10 elements and all the elements are set to zero. :{npZeros}")

#  b)  A 1-D array called vowels having the elements ‘a’, ‘e’, ‘i’, ‘o’ and ‘u’.
npVowels = np.array(['a','e','i','o','u'])
print(f"\nB) A 1-D array called vowels having the elements ‘a’, ‘e’, ‘i’, ‘o’ and ‘u’. :{npVowels}")

#  c)  A  2-D  array  called  ones  having  2  rows  and  5 columns  and  all  the  elements  are  set  to  1  and  dtype as int.
npDtype = np.ones((2,5),dtype='i')
print(f"\nC) A 2-D array called ones having 2 rows and 5 columns and all the elements are set to 1 and dtype as int. :\n{npDtype}")

#  d)  Use nested Python lists to create a 2-D array called  myarray1 having 3 rows and 3 columns and store the following data:  2.7,  -2,  -19  0,  3.4,  99.9  10.6,  0,  13
np2D = np.array([[2.7,-2,-19],[0, 3.4, 99.9],[10.6, 0, 13]])
print(f"\nD) Use nested Python lists to create a 2-D array called myarray1 having 3 rows and 3 columns and store the following data :\n{np2D}")

#  e)  A  2-D  array  called  myarray2  using  arange() having 3 rows and 5 columns with start value = 4, step size 4 and dtype as float.
npArrange = np.arange(4,62,4).reshape(3,5)
print(f"\nE) A 2-D array called myarray2 using arange() having 3 rows and 5 columns with start value = 4, step size 4 and dtype as float. :\n{npArrange}")


### Question 5

In [81]:
#   a)  Find the dimensions, shape, size, data type of the items  and  itemsize  of  arrays  zeros,  vowels,  ones, myarray1 and myarray2.
print(f"a)  Find the dimensions, shape, size, data type of the items  and  itemsize  of  arrays  zeros:{npZeros.ndim},  vowels:{npVowels.ndim},  ones:{np2D.ndim}, myarray1:{np2D.ndim} and myarray2 :{npArrange.ndim}")

#   b)  Reshape the array ones to have all the 10 elements in a single row.
print(f"b)  Reshape the array ones to have all the 10 elements in a single row \n{npZeros.reshape(2,5)}")


#   c)  Display the 2nd and 3rd element of the array vowels.
print(f"c)  Display the 2nd and 3rd element of the array vowels. {npVowels[1:3]}")


#   d)  Display all elements in the 2nd and 3rd row of the array myarray1.
print(f"d)  Display all elements in the 2nd and 3rd row of the array myarray1.\n{np2D[1:3]}")


#   e)  Display the elements in the 1st and 2nd column of the array myarray1.
print(f"e)  Display the elements in the 1st and 2nd column of the array myarray1.\n{np2D[:,:2]}")


#   f)  Display the elements in the 1st  column  of  the  2nd and 3rd row of the array myarray1.
print(f"f)  Display the elements in the 1st  column  of  the  2nd and 3rd row of the array myarray1.\n{np2D[:,0][1:3]}")


#   g)  Reverse the array of vowels.
print(f"g)  Reverse the array of vowels.{npVowels[::-1]}")

a)  Find the dimensions, shape, size, data type of the items  and  itemsize  of  arrays  zeros:1,  vowels:1,  ones:2, myarray1:2 and myarray2 :2
b)  Reshape the array ones to have all the 10 elements in a single row 
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
c)  Display the 2nd and 3rd element of the array vowels. ['e' 'i']
d)  Display all elements in the 2nd and 3rd row of the array myarray1.
[[ 0.   3.4 99.9]
 [10.6  0.  13. ]]
e)  Display the elements in the 1st and 2nd column of the array myarray1.
[[ 2.7 -2. ]
 [ 0.   3.4]
 [10.6  0. ]]
f)  Display the elements in the 1st  column  of  the  2nd and 3rd row of the array myarray1.
[ 0.  10.6]
g)  Reverse the array of vowels.['u' 'o' 'i' 'e' 'a']


### Question 6

In [82]:

#   a)  Divide all elements of array ones by 3.   
print(f"a)  Divide all elements of array ones by 3\n{npZeros/10}.")  

#   b)  Add the arrays myarray1 and myarray2.
npArrange = np.arange(0,100,5)
npArrange2 = np.arange(0,200,10)
print(f"b)  Add the arrays myarray1 and myarray2.\n {npArrange+npArrange2}")

#   c)  Subtract myarray1 from myarray2 and store the result in a new array.
npArrangeSubtract = npArrange-npArrange2
print(f"c)  Subtract myarray1 from myarray2 and store the result in a new array.\n {npArrangeSubtract}")

#   d)  Multiply myarray1 and myarray2 elementwise.
print(f"d)  Multiply myarray1 and myarray2 elementwise.\n {npArrange*npArrange2}")

#   e)  Do  the  matrix  multiplication  of  myarray1  and  myarray2  and  store  the  result  in  a  new  array  myarray3.
npMatrix = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
npMatrix2 = np.array([[11,22,33,44],[55,66,77,88],[99,110,111,112],[113,114,115,116]])
print(f"e)  Do  the  matrix  multiplication  of  myarray1  and  myarray2  and  store  the  result  in  a  new  array  myarray3.\n {np.matmul(npMatrix,npMatrix2)}")

#   f)  Divide myarray1 by myarray2.
print(f"f)  Divide myarray1 by myarray2.\n {npMatrix/npMatrix2}")

#   g)  Find  the  cube  of  all  elements  of  myarray1  and  divide the resulting array by 2. 
print(f"g)  Find  the  cube  of  all  elements  of  myarray1  and  divide the resulting array by 2.\n {np.divide(npMatrix**3,2)}") 

#   h)  Find the square root of all elements of myarray2  and  divide  the  resulting  array  by  2.  The  result   should be rounded to two places of decimals.
print(f"h)  Find the square root of all elements of myarray2  and  divide  the  resulting  array  by  2.  The  result   should be rounded to two places of decimals.\n {np.round(np.divide(npMatrix**3,2),decimals=2)}")


a)  Divide all elements of array ones by 3
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.].
b)  Add the arrays myarray1 and myarray2.
 [  0  15  30  45  60  75  90 105 120 135 150 165 180 195 210 225 240 255
 270 285]
c)  Subtract myarray1 from myarray2 and store the result in a new array.
 [  0  -5 -10 -15 -20 -25 -30 -35 -40 -45 -50 -55 -60 -65 -70 -75 -80 -85
 -90 -95]
d)  Multiply myarray1 and myarray2 elementwise.
 [    0    50   200   450   800  1250  1800  2450  3200  4050  5000  6050
  7200  8450  9800 11250 12800 14450 16200 18050]
e)  Do  the  matrix  multiplication  of  myarray1  and  myarray2  and  store  the  result  in  a  new  array  myarray3.
 [[ 870  940  980 1020]
 [1982 2188 2324 2460]
 [3094 3436 3668 3900]
 [4206 4684 5012 5340]]
f)  Divide myarray1 by myarray2.
 [[0.09090909 0.09090909 0.09090909 0.09090909]
 [0.09090909 0.09090909 0.09090909 0.09090909]
 [0.09090909 0.09090909 0.0990991  0.10714286]
 [0.11504425 0.12280702 0.13043478 0.13793103]]
g)  Find  the  cube  of  all  el

### Question 7

In [83]:

#   a)  Find the transpose of ones and myarray2.
print(f"a)  Find the transpose of ones and myarray2.\n{npMatrix.transpose()}\n\n{npMatrix2.transpose()}")

#   b)  Sort the array vowels in reverse.
print(f"b)  Sort the array vowels in reverse.\n {np.sort(npVowels)[::-1]}")

#   c)  Sort the array myarray1  such  that  it  brings  the  lowest value of the column in the first row and so on
print(f"c)  Sort the array myarray1  such  that  it  brings  the  lowest value of the column in the first row and so on\n{np.sort(npMatrix,axis=0)}")


a)  Find the transpose of ones and myarray2.
[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]

[[ 11  55  99 113]
 [ 22  66 110 114]
 [ 33  77 111 115]
 [ 44  88 112 116]]
b)  Sort the array vowels in reverse.
 ['u' 'o' 'i' 'e' 'a']
c)  Sort the array myarray1  such  that  it  brings  the  lowest value of the column in the first row and so on
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


### Question 8

In [84]:
#   a)  Use NumPy. split() to split the array myarray2 into  5  arrays  columnwise.  Store  your  resulting  arrays  in  myarray2A,  myarray2B,  myarray2C,  myarray2D  and  myarray2E.  Print  the  arrays  myarray2A, myarray2B, myarray2C, myarray2D and myarray2E.
npSplit = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20]
])
myarray2A, myarray2B, myarray2C, myarray2D, myarray2E = np.split(npSplit, 5, axis=1)
print(f"\na)  Use NumPy. split() to split the array myarray2 into  5  arrays  columnwise.")
print("myarray2A:\n", myarray2A)
print("myarray2B:\n", myarray2B)
print("myarray2C:\n", myarray2C)
print("myarray2D:\n", myarray2D)
print("myarray2E:\n", myarray2E)


#   b)  Split the array zeros at array index 2, 5, 7, 8 and store  the  resulting  arrays  in  zerosA,  zerosB, zerosC and zerosD and print them. 
zeros = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
zerosA, zerosB, zerosC, zerosD, zerosE = np.split(zeros, [2, 5, 7, 8])
print(f"\nb)  Split the array zeros at array index 2, 5, 7, 8")
print("zerosA:\n", zerosA)
print("zerosB:\n", zerosB)
print("zerosC:\n", zerosC)
print("zerosD:\n", zerosD)
print("zerosE:\n", zerosE)


#   c)  Concatenate the arrays myarray2A,  myarray2B # and myarray2C into an array having 3 rows and 3 columns
print(f"\nc)  Concatenate the arrays myarray2A,  myarray2B # and myarray2C into an array having 3 rows and 3 columns")
concatenated_array = np.concatenate((myarray2A, myarray2B, myarray2C), axis=1)
concatenated_array = np.delete(concatenated_array,2,axis=0)
reshaped_array = concatenated_array.reshape((3, 3))
print("Reshaped Array (3x3):\n", reshaped_array)


a)  Use NumPy. split() to split the array myarray2 into  5  arrays  columnwise.
myarray2A:
 [[ 1]
 [ 6]
 [11]
 [16]]
myarray2B:
 [[ 2]
 [ 7]
 [12]
 [17]]
myarray2C:
 [[ 3]
 [ 8]
 [13]
 [18]]
myarray2D:
 [[ 4]
 [ 9]
 [14]
 [19]]
myarray2E:
 [[ 5]
 [10]
 [15]
 [20]]

b)  Split the array zeros at array index 2, 5, 7, 8
zerosA:
 [0 1]
zerosB:
 [2 3 4]
zerosC:
 [5 6]
zerosD:
 [7]
zerosE:
 [8 9]

c)  Concatenate the arrays myarray2A,  myarray2B # and myarray2C into an array having 3 rows and 3 columns
Reshaped Array (3x3):
 [[ 1  2  3]
 [ 6  7  8]
 [16 17 18]]


### Question 9

In [85]:
# Create  a  2-D  array  called  myarray4  using  arange() having  14  rows  and  3  columns  with  start  value  =  -1,  step  size  0.25  having.  Split  this  array  row  wise  into  3  equal parts and print the result

rows = 14
cols = 3
myarray4 = np.arange(-1, -1 + rows * cols * 0.25, 0.25).reshape((rows, cols))
print("Original Array (myarray4):\n", myarray4)
split_arrays = np.array_split(myarray4, 3, axis=0)

for i, split_array in enumerate(split_arrays, start=1):
    print(f"Array part {i}:\n", split_array)


Original Array (myarray4):
 [[-1.   -0.75 -0.5 ]
 [-0.25  0.    0.25]
 [ 0.5   0.75  1.  ]
 [ 1.25  1.5   1.75]
 [ 2.    2.25  2.5 ]
 [ 2.75  3.    3.25]
 [ 3.5   3.75  4.  ]
 [ 4.25  4.5   4.75]
 [ 5.    5.25  5.5 ]
 [ 5.75  6.    6.25]
 [ 6.5   6.75  7.  ]
 [ 7.25  7.5   7.75]
 [ 8.    8.25  8.5 ]
 [ 8.75  9.    9.25]]
Array part 1:
 [[-1.   -0.75 -0.5 ]
 [-0.25  0.    0.25]
 [ 0.5   0.75  1.  ]
 [ 1.25  1.5   1.75]
 [ 2.    2.25  2.5 ]]
Array part 2:
 [[2.75 3.   3.25]
 [3.5  3.75 4.  ]
 [4.25 4.5  4.75]
 [5.   5.25 5.5 ]
 [5.75 6.   6.25]]
Array part 3:
 [[6.5  6.75 7.  ]
 [7.25 7.5  7.75]
 [8.   8.25 8.5 ]
 [8.75 9.   9.25]]


### Question 10

In [86]:
# a) Sum of all elements

sum_all_elements = np.sum(myarray4)
print("\na)Sum of all elements:", sum_all_elements)

# b) Sum of all elements row-wise
sum_row_wise = np.sum(myarray4, axis=1)
print("\nb)Sum of all elements row-wise:", sum_row_wise)

# c) Sum of all elements column-wise
sum_column_wise = np.sum(myarray4, axis=0)
print("\nc)Sum of all elements column-wise:", sum_column_wise)

# d) Max of all elements
max_element = np.max(myarray4)
print("\nd)Max of all elements:", max_element)

# e) Min of all elements in each row
min_row_wise = np.min(myarray4, axis=1)
print("\ne)Min of all elements in each row:", min_row_wise)

# f) Mean of all elements in each row
mean_row_wise = np.mean(myarray4, axis=1)
print("\nf)Mean of all elements in each row:", mean_row_wise)

# g) Standard deviation column-wise
std_dev_column_wise = np.std(myarray4, axis=0)
print("\ng)Standard deviation column-wise:", std_dev_column_wise)


a)Sum of all elements: 173.25

b)Sum of all elements row-wise: [-2.25  0.    2.25  4.5   6.75  9.   11.25 13.5  15.75 18.   20.25 22.5
 24.75 27.  ]

c)Sum of all elements column-wise: [54.25 57.75 61.25]

d)Max of all elements: 9.25

e)Min of all elements in each row: [-1.   -0.25  0.5   1.25  2.    2.75  3.5   4.25  5.    5.75  6.5   7.25
  8.    8.75]

f)Mean of all elements in each row: [-0.75  0.    0.75  1.5   2.25  3.    3.75  4.5   5.25  6.    6.75  7.5
  8.25  9.  ]

g)Standard deviation column-wise: [3.02334666 3.02334666 3.02334666]
