In [35]:
## Imports
import numpy as np
import pandas as pd

### Question 5

In [36]:
# Question A
series_a = pd.Series(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'])
print(f"Question A:\n{series_a}")

# Question B
series_b = pd.Series([0, 0, 0, 0, 0], index=['a', 'e', 'i', 'o', 'u'])
print(f"\nQuestion B:\n{series_b}")

# Question C
series_c = pd.Series({'ansh': 36, 'ankit': 35, 'tej': 8, 'trupal': 14, 'hiren': 34})
print(f"\nQuestion C:\n{series_c}")

# Question D
vowels = pd.Series([0, 0, 0, 0, 0], index=['a', 'e', 'i', 'o', 'u'])
print(f"\nQuestion D:\n{vowels.empty}")

# Question E
series_e = pd.Series(np.array([31, 28, 31, 30, 31, 30, 31, 30, 31, 30, 31, 30]), index=range(1, 13))
print(f"\nQuestion E:\n{series_e}")


Question A:
0     a
1     b
2     c
3     d
4     e
5     f
6     g
7     h
8     i
9     j
10    k
11    l
12    m
13    n
14    o
15    p
16    q
17    r
18    s
19    t
20    u
21    v
22    w
23    x
24    y
25    z
dtype: object

Question B:
a    0
e    0
i    0
o    0
u    0
dtype: int64

Question C:
ansh      36
ankit     35
tej        8
trupal    14
hiren     34
dtype: int64

Question D:
False

Question E:
1     31
2     28
3     31
4     30
5     31
6     30
7     31
8     30
9     31
10    30
11    31
12    30
dtype: int64


### Question 6

In [37]:
vowels['a':'u']=10
print(f"\nQuestion A :\n{vowels}")

print(f"\nQuestion B :\n{vowels/2}")

vowels1 = vowels.copy()
vowels1['a':'u'] = 2,5,6,3,8
print(f"\nQuestion C :\n{vowels1}")

vowels3 = vowels + vowels1
print(f"\nQuestion D :\n{vowels3}")

print(f"\nQuestion E :\nSubtract\n{vowels-vowels1}\nMultiply\n{vowels*vowels1}\nDivide\n{vowels/vowels1}")

vowels1.index = 'A','E','I','O','U'
print(f"\nQuestion F :\n{vowels1}")


Question A :
a    10
e    10
i    10
o    10
u    10
dtype: int64

Question B :
a    5.0
e    5.0
i    5.0
o    5.0
u    5.0
dtype: float64

Question C :
a    2
e    5
i    6
o    3
u    8
dtype: int64

Question D :
a    12
e    15
i    16
o    13
u    18
dtype: int64

Question E :
Subtract
a    8
e    5
i    4
o    7
u    2
dtype: int64
Multiply
a    20
e    50
i    60
o    30
u    80
dtype: int64
Divide
a    5.000000
e    2.000000
i    1.666667
o    3.333333
u    1.250000
dtype: float64

Question F :
A    2
E    5
I    6
O    3
U    8
dtype: int64


### Question 7

In [38]:
print(f"\nQuestion A :\n{vowels.ndim}")

vowels.name = "Vowels"
print(f"\nQuestion B :\n{vowels}")

Friends = pd.Series({'ansh':36,'ankit':35,'tej':8,'trupal':14,'hiren':34})
MonthDays = pd.Series(np.array([31,28,31,30,31,30,31,30,31,30,31,30]),index=range(1,13))
Friends.index.name = "Students"
MonthDays.index.name = "Months"
print(f"\nQuestion C :\n{Friends}\n\n{MonthDays}")

print(f"\nQuestion D :\n{Friends[1:3]}")

EngAlh = pd.Series(['a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z'])
print(f"\nQuestion E :\n{EngAlh[4:-10]}")

print(f"\nQuestion F :\n{EngAlh[:11]}")

print(f"\nQuestion G :\n{EngAlh[:-11:-1]}")


Question A :
1

Question B :
a    10
e    10
i    10
o    10
u    10
Name: Vowels, dtype: int64

Question C :
Students
ansh      36
ankit     35
tej        8
trupal    14
hiren     34
dtype: int64

Months
1     31
2     28
3     31
4     30
5     31
6     30
7     31
8     30
9     31
10    30
11    31
12    30
dtype: int64

Question D :
Students
ankit    35
tej       8
dtype: int64

Question E :
4     e
5     f
6     g
7     h
8     i
9     j
10    k
11    l
12    m
13    n
14    o
15    p
dtype: object

Question F :
0     a
1     b
2     c
3     d
4     e
5     f
6     g
7     h
8     i
9     j
10    k
dtype: object

Question G :
25    z
24    y
23    x
22    w
21    v
20    u
19    t
18    s
17    r
16    q
dtype: object


In [39]:
print(f"\nQuestion A :\n")
MonthDays = pd.Series({
    1: 'January', 2: 'February', 3: 'March', 4: 'April', 5: 'May',
    6: 'June', 7: 'July', 8: 'August', 9: 'September', 10: 'October',
    11: 'November', 12: 'December'
})
print(MonthDays[3:8])
print(f"\nQuestion B :\n{MonthDays[::-1]}")


Question A :

4     April
5       May
6      June
7      July
8    August
dtype: object

Question B :
12     December
11     November
10      October
9     September
8        August
7          July
6          June
5           May
4         April
3         March
2      February
1       January
dtype: object


### Question 9

In [40]:
listVal = {
'2014': pd.Series([100.5,12000,2000,50000],index=['Kusum','Kinshuk','Ankit','Shruti']),
'2015': pd.Series([150.8,18000,50000,60000],index=['Kusum','Kinshuk','Ankit','Shruti']),
'2016': pd.Series([200.9,22000,70000,70000],index=['Kusum','Kinshuk','Ankit','Shruti']),
'2017': pd.Series([30000,30000,10000,80000],index=['Kusum','Kinshuk','Ankit','Shruti']),
'2018': pd.Series([40000,45000,125000,90000],index=['Kusum','Kinshuk','Ankit','Shruti'])    
}
listVal = pd.DataFrame(listVal)
print(listVal)

            2014     2015     2016   2017    2018
Kusum      100.5    150.8    200.9  30000   40000
Kinshuk  12000.0  18000.0  22000.0  30000   45000
Ankit     2000.0  50000.0  70000.0  10000  125000
Shruti   50000.0  60000.0  70000.0  80000   90000


### Question 10

In [41]:
print(f"\nQuestion A :\n{listVal.index}")
print(f"\nQuestion B :\n{listVal.columns}")
print(f"\nQuestion C :\n{listVal.dtypes}")
print(f"\nQuestion D :\n")
print("Dimensions:", listVal.ndim)
print("Shape:", listVal.shape)
print("Size:", listVal.size)
print("Values:\n", listVal.values)

print(f"\nQuestion E :\n{listVal.tail(2)}")
print(f"\nQuestion F :\n{listVal.iloc[:, :2]}")

data = {
    '2018': pd.Series([160000, 110000, 500000, 340000, 900000], index=['Madhu', 'Kusum', 'Kinshuk', 'Ankit', 'Shruti'])
}
Sales2 = pd.DataFrame(data)
print(f"\nQuestion G :\n{Sales2}")
print(f"\nQuestion H :\n{Sales2.empty}")




Question A :
Index(['Kusum', 'Kinshuk', 'Ankit', 'Shruti'], dtype='object')

Question B :
Index(['2014', '2015', '2016', '2017', '2018'], dtype='object')

Question C :
2014    float64
2015    float64
2016    float64
2017      int64
2018      int64
dtype: object

Question D :

Dimensions: 2
Shape: (4, 5)
Size: 20
Values:
 [[1.005e+02 1.508e+02 2.009e+02 3.000e+04 4.000e+04]
 [1.200e+04 1.800e+04 2.200e+04 3.000e+04 4.500e+04]
 [2.000e+03 5.000e+04 7.000e+04 1.000e+04 1.250e+05]
 [5.000e+04 6.000e+04 7.000e+04 8.000e+04 9.000e+04]]

Question E :
           2014     2015     2016   2017    2018
Ankit    2000.0  50000.0  70000.0  10000  125000
Shruti  50000.0  60000.0  70000.0  80000   90000

Question F :
            2014     2015
Kusum      100.5    150.8
Kinshuk  12000.0  18000.0
Ankit     2000.0  50000.0
Shruti   50000.0  60000.0

Question G :
           2018
Madhu    160000
Kusum    110000
Kinshuk  500000
Ankit    340000
Shruti   900000

Question H :
False


### Question 11

In [51]:
# a) Append Sales2 to Sales
Sales = pd.concat([listVal, Sales2], axis=0)
print("After appending Sales2:\n", Sales)

# b) Transpose Sales
Sales = Sales.T
print("After transposing:\n", Sales)

# c) Sales in 2017
print("Sales in 2017:\n", Sales.loc['2017'])

# d) Sales by Madhu and Ankit in 2017 and 2018
print("Sales by Madhu and Ankit in 2017 and 2018:\n", Sales.loc[['2017', '2018'], ['Madhu', 'Ankit']])

# e) Sales by Shruti in 2016
print("Sales by Shruti in 2016:\n", Sales.loc['2016', 'Shruti'])

# f) Add data for Sumeet
Sumeet_data = [196.2, 37800, 52000, 78438, 38852]
Sales.loc['Sumeet'] = Sumeet_data
print("After adding Sumeet's data:\n", Sales)

# g) Delete the data for the year 2014
Sales = Sales.drop('2014', axis=0)
print("After deleting the year 2014:\n", Sales)

# h) Delete the data for Kinshuk
Sales = Sales.drop('Kinshuk', axis=1)
print("After deleting Kinshuk's data:\n", Sales)

# i) Rename Ankit to Vivaan and Madhu to Shailesh
Sales = Sales.rename(columns={'Ankit': 'Vivaan', 'Madhu': 'Shailesh'})
print("After renaming:\n", Sales)

# j) Update Shailesh's sale in 2018 to 100000
Sales.loc['2018', 'Shailesh'] = 100000
print("After updating Shailesh's sale in 2018:\n", Sales)

# k) Write Sales to a CSV file without row and column labels
Sales.to_csv('SalesFigures.csv', header=False, index=False)

# l) Read the CSV file into SalesRetrieved and update labels
SalesRetrieved = pd.read_csv('SalesFigures.csv', header=None)
SalesRetrieved.index = Sales.index
SalesRetrieved.columns = Sales.columns
print("SalesRetrieved DataFrame:\n", SalesRetrieved)


After appending Sales2:
             2014     2015     2016     2017    2018
Kusum      100.5    150.8    200.9  30000.0   40000
Kinshuk  12000.0  18000.0  22000.0  30000.0   45000
Ankit     2000.0  50000.0  70000.0  10000.0  125000
Shruti   50000.0  60000.0  70000.0  80000.0   90000
Madhu        NaN      NaN      NaN      NaN  160000
Kusum        NaN      NaN      NaN      NaN  110000
Kinshuk      NaN      NaN      NaN      NaN  500000
Ankit        NaN      NaN      NaN      NaN  340000
Shruti       NaN      NaN      NaN      NaN  900000
After transposing:
         Kusum  Kinshuk     Ankit   Shruti     Madhu     Kusum   Kinshuk  \
2014    100.5  12000.0    2000.0  50000.0       NaN       NaN       NaN   
2015    150.8  18000.0   50000.0  60000.0       NaN       NaN       NaN   
2016    200.9  22000.0   70000.0  70000.0       NaN       NaN       NaN   
2017  30000.0  30000.0   10000.0  80000.0       NaN       NaN       NaN   
2018  40000.0  45000.0  125000.0  90000.0  160000.0  110000.

ValueError: cannot set a row with mismatched columns